// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtbTPA-jYk6J6eFengKkVYTaBogD2E3A',
    appId: '1:1079457396889:web:5f8d8635f3d92d0bc2a008',
    messagingSenderId: '1079457396889',
    projectId: 'chatty-670c5',
    authDomain: 'chattyapp.firebaseapp.com',
    storageBucket: 'chattyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5VqerJO_qc-pNrsI9FeyBWTjnW_0GN0',
    appId: '1:18718766269:android:8a5bf45c1d14ec168cb3d4',
    messagingSenderId: '1079457396889',
    projectId: 'chatty-670c5',
    storageBucket: 'chattyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_aJVLEI6YE3MtWg_G3vwhwSiBKIgcW8',
    appId: '1:1079457396889:ios:7af57ed5bab562a2c2a008',
    messagingSenderId: '1079457396889',
    projectId: 'chatty-670c5',
    storageBucket: 'chattyapp.appspot.com',
    iosBundleId: 'com.ahmedtsalem.ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_aJVLEI6YE3MtWg_G3vwhwSiBKIgcW8',
    appId: '1:1079457396889:ios:c4efa43d120e1888c2a008',
    messagingSenderId: '1079457396889',
    projectId: 'chatty-670c5',
    storageBucket: 'com.ahmedtsalem.ChatApp',
    iosBundleId: 'com.example.qataf.RunnerTests',
  );
}
